### ISSUE TITLE
/compatibilty Report not working

### ISSUE THREAD

**Issue by siprbaum** [nunit-legacy/nunitv2#50]
It looks like the following line

https://github.com/nunit-legacy/nunitv2/blob/29d2db2c028da485e7e615d25482c75257ca4930/src/NUnitCore/core/Compatibility.cs#L29

opens up a FileStream, which is never closed.
This causes trouble when the file is later opened again to append the actual report to it.

Actual Exception:
NUnit-Console.exe compatibility-tests.dll /nologo /compat
ProcessModel: Default    DomainUsage: Single
Execution Runtime: net-4.5
Unhandled Exception:
System.IO.IOException: The process cannot access the file 'C:\####\COMPATIBILITY.TXT' because it is being used by another process.
...

**Comment by CharliePoole** [comment]
I'll check it out. It's a bit odd that I haven't had the problem myself. Are you using a release or building from master?

**Comment by siprbaum** [comment]
Sadly, I have a local build with modifications of NUnit here (don't ask), but those shouldn't have any influence.
The `BeginCollection` method, which is just below the `Initialize` method referenced above, 
tries to open a new StreamWriter with the existing `COMPATIBILITY.TXT` file and fails because the
file is already open by the `FileStream` created by the `File.Create`

**Comment by siprbaum** [comment]
I only run `nunit-console.exe compatibility-tests.dll /nologo /compat`, so no parallel test execution
or other fancy stuff going on.

The FileStream returned by `File.Create(_workFilePath)` in the `Initialize` method is never closed.
If I modify the `Initialize` method to look like this:
```
public static void Initialize(string workDirectory)
{
    _workFilePath = Path.Combine(workDirectory, WORK_FILE);
    var fs = File.Create(_workFilePath);
    fs.Close();
}
```
then I no longer get the exception that the COMPATIBILITY.TXT is already open and everything
works as expected.

Just for reference: I don't use any of the csproj files from NUnit. I (was forced to) use csproj files which
fit in the rest of the build system, so TargetFramework and other stuff might be different. 
Not sure if it matters, I just want to mention it.

**Comment by CharliePoole** [comment]
Confirmed in AppVeyor even though it doesn't fail in my local build.
