### ISSUE TITLE
nunit.framework is loaded by partial name in nunit.core

### ISSUE THREAD

**Issue by cyanite** [nunit-legacy/nunitv2#62]
This bug is similar to the one I fixed in NUnit 3, see there for further discussion: https://github.com/nunit/nunit-console/issues/367

In this case it's even simpler, since we have the actual assembly available to us and don't even need to load it at all. I'll submit a PR in a moment with a fix.

In NUnit 2, the problem is confined to activating ITestActions, as everything else is loaded correctly. This, however, is something we use a lot in our test suites.

(IMO Microsoft made a mistake by making it possible to load by partial name; it causes stuff to work...until it doesn't.)

**Comment by CharliePoole** [comment]
My confusion with this issue is due to the fact that NUnit V2 doesn't support .NET Core!

**Comment by cyanite** [comment]
@CharliePoole hm? The issue isn't related to .NET Core. I don't use .NET Core myself. The issue affects .NET Framework. It's triggered when an app.config applies a policy to the nunit.framework dll, placing it at a different location. This is the same as the linked issue above, and happens for the same reasons: loading by partial name (which doesn't apply policies).

**Comment by CharliePoole** [comment]
Ah... sorry! I read nunit.core in the title as .NET core.

**Comment by CharliePoole** [comment]
See my comment on your PR #63

**Comment by CharliePoole** [comment]
@cyanite I noticed that this change introduced another place where we have to update the version for each release. Can you think of any way to avoid that?
