### ISSUE TITLE
Create an ID filter

### ISSUE THREAD

**Issue by CharliePoole** [nunit-legacy/nunitv2#75]
Currently, such would not be used by any runners. However, by creating it, we would enable the NUnit 3 engine's V2 Framework Driver extension to translate ID filters, which are used by the TestCentric GUI.

We currently have a "Name filter" based on TestName. In nunitv2, TestName consists of both an ID and the full name of the test. If the ID is not provided, then the name alone is used.

For this issue, we would create a separate filter that provides __only__ a test id. It would need to have thorough tests, since it would otherwise not be exercised by nunitv2. Once this exists, we can move to resolving issue nunit/nunit-v2-framework-driver#29 and then TestCentric/testcentric-gui#340.

**Comment by CharliePoole** [comment]
@mikkelbu I gather this is what you asked about on the GUI issue... If you want to work on it, I can point you to the right bits to concentrate on.

**Comment by CharliePoole** [comment]
@mikkelbu Are you still planning to work on this?

**Comment by mikkelbu** [comment]
@CharliePoole I had planned to work on this, but I've not had much time the last couple of weeks, and the coming weeks also look busy. So if you want to take over the issue you are most welcome.

**Comment by CharliePoole** [comment]
Working on a critical issue in my spare time right now. I'll take a look when I get freed up.

**Comment by CharliePoole** [comment]
@mikkelbu I'm doing this one now.
