### ISSUE TITLE
Loosen restriction of only one top-level test suite in XSD

### ISSUE THREAD

**Issue by CharliePoole** [nunit-legacy/nunitv2#80]
Issue nunit/nunit-v2-result-writer#13 points out that the XSD only permits a single top-level suite under the `<test-results>` element of the V2 test results file. The V2 console and gui runners conform to that definition but the NUnit 3 V2 result writer extension doesn't. In fact, it __cannot__ if we are to support all possible V3 command lines, including multiple projects or projects mixed with assemblies.

As a compromise resolution for this, I'm proposing to modify the XSD in the next legacy release  to loosen the restriction and allow multiple top-level test suites.

Note that this change will only be visible to those using the next (2.7.2) legacy release.

Comments?
@nfalco79 @NikolayPianikov

**Comment by siprbaum** [comment]
Are you sure yo mean **3**.7.2? The last tagged version is **2**.7.1 so I would assume you actually mean **2.7.2**

**Comment by CharliePoole** [comment]
Correct: 2.7.2
