### ISSUE TITLE
Release Notes links to http://nunitsoftware.com dead

### ISSUE THREAD

**Issue by jmairboeck** [nunit-legacy/nunitv2#82]
It seems that the domain [http://nunitsoftware.com/](http://nunitsoftware.com/) has expired and the linked release notes on the Releases pages are not available any more.

**Comment by CharliePoole** [comment]
I thought I had fixed the links! Thanks for reporting this.

**Comment by jmairboeck** [comment]
The releases for 2.7.1 and 2.6.5 contain links to that domain. 2.6.6 points to this Github repository. 2.6.7 and 2.7.0 don't contain any links to release notes.

**Comment by CharliePoole** [comment]
I'll fix up a temporary link to my dormant site tomorrow while I think about how to deal with this in the long term.

**Comment by maettu-this** [comment]
Issue persists, https://github.com/nunit-legacy/nunitv2/releases refers to http://nunitsoftware.com/nunitv2/index.php?p=releaseNotes&r=2.7.1 which results in:

![grafik](https://github.com/nunit-legacy/nunitv2/assets/24897735/0673c294-ae8e-46da-94e6-aea3abc2ad44)

**Comment by mikkelbu** [comment]
@CharliePoole It seems like we (I guess it was you) no long own nunitsoftware.com. So I guess we either need to remove the links and make the point to somewhere else?

**Comment by CharliePoole** [comment]
Thanks for the reminder... I used the GitHub feature to generate release notes for every release. I'll look at nunit-project-editor as well.
