### ISSUE TITLE
nunit-agent.exe is throwing System.DllNotFoundException: Unable to load DLL 'rasapi32.dll' exception in Windows 2022 server

### ISSUE THREAD

**Issue by sravankumarkurma** [nunit-legacy/nunitv2#83]
when we launch nunit-console.exe using PsExec.exe from a command line. it is throwing an error Unable to load DLL 'rasapi32.dll' exception. reviewed the process monitor with Microsoft support in Windows 2022 server and identified that nunit-agent.exe is erroring out with this error. we don't have this issue in Windows 2016 and 2019 servers. 

nunit-console.exe version - 2.6.4.14350

**Comment by CharliePoole** [comment]
As indicated in the README, this project is primarily intended to support folks who must must continue to use NUnit V2. The major reason for this need is that they are continuing to work on older platforms. If you are using Windows 2022 Server, you would be better advised to convert your tests to NUnit3. Alternatively, you can try running under the NUnit3 console runner using the NUnit V2 Framework driver extension. That extension, however, is based on the same code as this project, so you may run into a similar problem there. In addition, be advised that the next major version of the NUnit console runner will most likely drop support for the NUnit V2 extension.
